# .gitpod.yml
tasks:
  - name: "Install Sui Command"
    init: |
      wget https://github.com/MystenLabs/sui/releases/download/mainnet-v1.37.3/sui-mainnet-v1.37.3-ubuntu-x86_64.tgz
      tar -xzf sui-mainnet-v1.37.3-ubuntu-x86_64.tgz -C /usr/local/bin

ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - dbaeumer.vscode-eslint # 安装 ESLint 扩展
    - esbenp.prettier-vscode # 安装 Prettier 扩展

# image:
#   file: Dockerfile