# .gitpod.yml
tasks:
  - name: "Install Sui Command"
    init: |
      wget https://github.com/MystenLabs/sui/releases/download/mainnet-v1.37.3/sui-mainnet-v1.37.3-ubuntu-x86_64.tgz
      sudo tar -xzf sui-mainnet-v1.37.3-ubuntu-x86_64.tgz -C /usr/local/bin
      
  - name: "Install Walrus"
    init: |
      wget https://storage.googleapis.com/mysten-walrus-binaries/walrus-testnet-latest-ubuntu-x86_64-generic
      sudo mv walrus-testnet-latest-ubuntu-x86_64-generic /usr/local/bin/walrus
      sudo chmod +x /usr/local/bin/walrus

  - name: "Init Sui dapp development environment"
    init: |
      pnpm install

  - name: "Install Sui site builder"
    init: |
      export CARGO_BUILD_JOBS=12
      git clone https://github.com/MystenLabs/walrus-sites.git
      cd walrus-sites/site-builder
      cargo install --path .

      

ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - dbaeumer.vscode-eslint # 安装 ESLint 扩展
    - esbenp.prettier-vscode # 安装 Prettier 扩展

# image:
#   file: Dockerfile