# module: site
# portal: walrus.site
package: 0xc5bebae319fc9d2a9dc858b7484cdbd6ef219decf4662dc81a11dc69bb7a5fa7
general:
  rpc_url: https://fullnode.testnet.sui.io:443
  wallet: /home/gitpod/.sui/sui_config/client.yaml
  walrus_binary: /usr/local/bin/walrus
  walrus_config: /workspace/gitpod-template/client_config.yaml
  gas_budget: 50000000
